### ISSUE TITLE
Message id should be string, not number

### ISSUE THREAD

**Issue by sorenbs** [apollographql/subscriptions-transport-ws#173] opened 2017-06-10 13:27 UTC
The client sends messages with `number` ids (https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/client.ts#L395)

This is in direct contradiction to the protocol specification stating that ids must be of type `string` (https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md)

Am I missing something here?

**Comment by DxCx** [comment] 2017-06-10 14:17
hey @sorenbs thanks for noticing that..
the issue is with the PROTOCOL.md file, we need to fix it to `number`. 👍 

but since you raised that up, do you see any reason it should be `string` and not `number`?

**Comment by sorenbs** [comment] 2017-06-10 17:47
Thanks @DxCx :-)

Unless you want to enforce the semantic meaning of a number, I actually think it would make more sense to stick with String. At Graphcool we are treating string as the normal case and have a "temporary" workaround to also support numbers.

If you have time - I would love to get your take on an issue I am currently facing in the subscriptions channel in the Apollo slack.

**Comment by DxCx** [comment] 2017-06-10 18:45
hmm i just think that num+1 costs less then randomized string
can you give an example where string makes more sense?

**Comment by sorenbs** [comment] 2017-06-10 21:41
You could still use String(num+1) in the Apollo client :-)

Hopefully this specification for a ws-based transport will gain broader adoption than Apollo, so I think it is worth it to consider the semantic meaning.

The only disadvantage to using a string I can see is that `"1"` requires more bandwidth than `1`, but that's a worthy tradeoff imho.

**Comment by DxCx** [comment] 2017-06-11 05:58
since the real meaning of the `id` is tagging, and numbering doesn't really matter, that sounds legit... in the future it can be used for some kind of cacheing (for queries) and such..
@mistic can you please open a PR changing `id` from `number` to `string`?
we are using it as an object key anyway and we are not enforcing anything

**Comment by dotansimha** [comment] 2017-06-12 09:02
Fixed in 0.7.2! 🎉 🎉

**Closed by dotansimha** 2017-06-12 09:02 UTC
Labels: bug, waiting-for-release
