### ISSUE TITLE
addGraphQLSubscriptions issue

### ISSUE THREAD

**Issue by luthfirrahmanb** [apollographql/subscriptions-transport-ws#324] opened 2017-12-21 01:37 UTC
Hi guys i've got an error like this `TypeError: Object(...) is not a function`
and my code like this

`const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
    wsClient,
    networkInterface
)`

any ideas? i'm really confused

**Comment by naokikurosawa** [comment] 2018-01-08 03:32
I tried to find out this because I have same problem.

`addGraphQLSubscriptions` was deprecated. And it was removed since v0.9.0.
README doc is stale for a long time! :-(

**Comment by NeoPhi** [comment] 2018-01-09 14:25
Closing as duplicate of https://github.com/apollographql/subscriptions-transport-ws/issues/284

**Closed by NeoPhi** 2018-01-09 14:25 UTC
