### ISSUE TITLE
Every few minutes the Websocket closed with onError event - Android 

### ISSUE THREAD

**Issue by schavaLogi** [apollographql/subscriptions-transport-ws#483] opened 2018-11-01 12:38 UTC
In Android mobile with the react-native framework, the socket is closed on every 4 ~ 5 mins with onError 

Log:
 I/ReactNativeJS: 'State changed to onerror - Remote party', { type: 'error',
                                                                      target: 
                                                                       { CONNECTING: 0,
                                                                         OPEN: 1,
                                                                         CLOSING: 2,
                                                                         CLOSED: 3,
                                                                         readyState: 3,
                                                                         _eventEmitter: 
                                                                          { _subscriber: 
                                                                             { _subscriptionsForType: 
                                                                                { appStateDidChange: 
                                                                                   [ { subscriber: [Circular],
                                                                                       emitter: 
                                                                                        { _subscriber: [Circular],
                                                                                          isAvailable: true,
                                                                                          _eventHandlers: 
                                                                                           { change: 
                                                                                              { _mapData: [ [Object], [Object], [Object], [Object] ],
                                                                                                _objectIndex: { '2': 0, '4': 1, '7': 2, '11': 3 },
                                                                                                _stringIndex: {},
                                                                                                _otherIndex: {} },
                                                                                             memoryWarning: 
                                                                                              { _mapData: [],
                                                                                                _objectIndex: {},
                                                                                                _stringIndex: {},
                                                                                                _otherIndex: {} } },
                                                                                          currentState: 'active' },
                                                                                       listener: [Function],
                                                                                       context: undefined,
                                                                                       eventType: 'appStateDidChange',
                                                                                       key: 0 },
                                                                                     { subscriber: [Circular],
                                                                                       emitter: 
                                                                                        { _subscriber: [Circular],
                                                                                          isAvailable: true,
                                                                                          _eventHandlers: 
                                                                                           { change: 
                                                                                              { _mapData: [ [Object], [Object], [Object], [Object] ],
                                                                                                _objectIndex: { '2': 0, '4': 1, '7': 2, '11': 3 },
                                                                                                _stringIndex: {},
                                                                                                _otherIndex: {} },
                                                                                             memoryWarning: 
                                                                                              { _mapData: [],
                                                                                                _objectIndex: {},
                                                                                                _stringIndex: {},
                                                                                                _otherIndex: {} } },
                                                                                          currentState: 'active' },
                                                                                       listener: [Function],
                                                                                       context: undefined,
                                                                                       eventType: 'appStateDidChange',
                                                                                       key: 1 },
                                                                                     { subscriber: [Circular],
                                                                                       emitter: 
                                                                                        { _subscriber: [Circular],
                                                                                          isAvailable: true,
                                                                                          _eventHandlers: 
                                                                                           { change: 
                                                                                              { _mapData: [ [Object], [Object], [Object], [Object] ],
                                                                                                _objectIndex: { '2': 0, '4': 1, '7': 2, '11': 3 },
                                                                                                _stringIndex: {},
                                                                                                _otherIndex: {} },
                                                                                             memoryWarning: 
                                                                                              { _mapData: [],
                                                                                                _objectIndex: {},
                                                                                                _stringIndex: {},
                                                                                                _otherIndex: {} } },
                                                                                          currentState: 'active' },
                                                                                       listener: [Function],
                                                                                       context: undefined,
                                                                                       eventType: 'appStateDidChange',
                                                                                       key: 2 },
                                                                                     { subscriber: [Circular],
                                                                                       emitter: 
                                                                                        { _subscriber: [Circular],
                                                                                          isAvailable: true,
                                                                                          _eventHandlers: 
                                                                                           { change: 
                                                                                              { _mapData: [ [Object], [Object], [Object], [Object] ],
                                                                                                _objectIndex: { '2': 0, '4': 1, '7': 2, '11': 3 },
                                                                                                _stringIndex: {},
                                                                                                _otherIndex: {} },
                                                                                             memoryWarning: 
                                                                                              { _mapData: [],
                                                                                                _objectIndex: {},
                                                                                                _stringIndex: {},
                                                                                                _otherIndex: {} } },
                                                                                          currentState: 'active' },
                                                                                       listener: [Function],
                                                                                       context: undefined,
                                                                                       eventType: 'appStateDidChange',
                                                                                       key: 3 },
                                                                                     { subscriber: [Circular],
                                                                                       emitter: 
                                                                                        { _subscriber:
 I/ReactNativeJS: Thu Nov  1 18:01:17 2018, "Generic Console", "takeOverConsole", [{"0":"State changed to onclose - Remote party"}]
 I/ReactNativeJS: State changed to onclose - Remote party

**Comment by perrosnk** [comment] 2018-11-14 16:16
+1 @schavaLogi Did you find any solution?

**Comment by perrosnk** [comment] 2018-11-14 17:10
@schavaLogi What was the solution to the other 2 (issues) [issue](https://github.com/apollographql/subscriptions-transport-ws/issues/372) [issue](https://github.com/apollographql/subscriptions-transport-ws/issues/352) you have closed? 

Could these two be related?

There also seems to be another open [issue](https://github.com/apollographql/subscriptions-transport-ws/issues/490) that could be related.

I believe we should make a guide with best practices and guidance on how to use this library with react native

**Comment by farzd** [comment] 2018-11-14 17:30
@perrosnk lol this is painful. I think its React-Native, its closing the socket connection. The keepAlive gets interrupted if the socket disconnects. I'm gonna try replicate on the web and try on a fresh React-Native project

**Comment by schavaLogi** [comment] 2018-11-16 04:07
> +1 @schavaLogi Did you find any solution?

I am waiting for community help as it is purely mobile platform specific disconnect

**Comment by schavaLogi** [comment] 2018-11-16 04:08
> @schavaLogi What was the solution to the other 2 (issues) [issue](https://github.com/apollographql/subscriptions-transport-ws/issues/372) [issue](https://github.com/apollographql/subscriptions-transport-ws/issues/352) you have closed?
> 
> Could these two be related?
> 
> There also seems to be another open [issue](https://github.com/apollographql/subscriptions-transport-ws/issues/490) that could be related.
> 
> I believe we should make a guide with best practices and guidance on how to use this library with react native

I mentioned the reason and solution in those specific issues. we adjusted timeout and keepalive interval in our servers.

**Comment by farzd** [comment] 2018-11-16 16:57
> > +1 @schavaLogi Did you find any solution?
> 
> I am waiting for community help as it is purely mobile platform specific disconnect

Well it happens on iOS as well!

**Comment by forbesgillikin** [comment] 2018-11-17 22:36
I am experiencing this on iOS as well. Any info would be great!

**Comment by forbesgillikin** [comment] 2018-12-01 01:48
This issue is not happening on my local machine. Only when the updates are done on a Digital Ocean Ubuntu server. Do the Keep Alive settings need to change on the server?

**Comment by farzd** [comment] 2018-12-01 07:59
thats interesting @forbesgillikin, i get the same issue on local and remote

**Comment by slawomir-brzezinski-at-clarksons** [comment] 2018-12-19 16:16
We're also seem to be experiencing a similar issue. I think diagnostics of these would be easier if #505 was addressed first, so users are allowed to log the reason for disconnetions (and maybe learn that the issue is with their setup).

**Comment by danielehrhardt** [comment] 2020-10-31 15:41
Did someone find out a Solution for this?

**Closed** 2022-03-03 22:36 UTC
