### ISSUE TITLE
WebSocket connection closing occasionally

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/subscriptions-transport-ws#381] opened 2018-03-22 17:41 UTC
After building a VueJS app with Apollo Server graphql and vue-apollo for the client, the socket is occasionally disconnected on the first load itself. (It won't happen every time, maybe once in every 5-10 loads). Whats the reason for this?

![152173961846741591](https://user-images.githubusercontent.com/23092846/37787965-3e318054-2e26-11e8-8e37-644e9d44961c.gif)
![screenshot from 2018-03-22 21-24-13](https://user-images.githubusercontent.com/23092846/37787977-4363dce8-2e26-11e8-830f-976d45ebabb3.png)

**Comment by mxstbr** [comment] 2018-03-22 18:38
We're experiencing the same thing, I think it was due to #368—that was released yesterday in 0.9.7, mind updating to that and letting me know if it still happens?

**Comment by gijo-varghese** [comment] 2018-03-22 18:40
Ok. Let me try downgrading. Which version do you prefer?

**Comment by mxstbr** [comment] 2018-03-22 19:02
Upgrading, not downgrading! I think #368 fixes it, sorry for the bad wording there

**Comment by gijo-varghese** [comment] 2018-03-23 00:42
Already using 0.9.7. The issue still exists :(

**Comment by gijo-varghese** [comment] 2018-03-23 07:33
Finally 
```
link.subscriptionClient.maxConnectTimeGenerator.duration = () => link.subscriptionClient.maxConnectTimeGenerator.max
```
That fixed the issue

Thanks to https://github.com/apollographql/subscriptions-transport-ws/issues/377

**Comment by mxstbr** [comment] 2018-03-23 07:36
Hmm interesting, how could we/should we implement this by default? Mind submitting a PR so we can discuss?

**Comment by gijo-varghese** [comment] 2018-03-23 08:11
I think we should increment the default handshake from 1 request to 3/5 seconds. Also make it available as an option to set, so that users can specify their own timeout for the handshake. What do you think?

**Comment by mxstbr** [comment] 2018-03-23 08:13
I don't know, I'm not familiar with the problem domain! Submit a PR, explain your reasoning and then we can discuss—it's hard for me to say without looking at a patch :blush:

**Comment by gijo-varghese** [comment] 2018-03-23 08:14
Sure. I'm at the end of a product deployment. I'll send it soon :)

**Comment by mxstbr** [comment] 2018-03-23 08:15
Awesome, thank you!

**Comment by gijo-varghese** [comment] 2018-03-24 16:27
Figured out one more thing. We've to add `lazy: true`.

**Comment by mxstbr** [comment] 2018-03-24 20:25
PRs very welcome!

**Comment by arsanjea** [comment] 2018-04-09 20:30
hey @gijo-varghese . While the fix mentioned in https://github.com/apollographql/subscriptions-transport-ws/issues/377 make things better, the subscription client still disconnects every 30-45 seconds, which makes for a pretty poor experience for my customers :/

**Comment by gijo-varghese** [comment] 2018-04-10 05:28
@arsanjea I just checked. For me, it's not disconnecting after 30-45 secs. Are you sure?

**Comment by arsanjea** [comment] 2018-04-10 14:44
@gijo-varghese yeah, does. But I am not using ```lazy: true``` since I won't be able to use my fix if the client is not instantiated right away.
Would you mind sharing your instentiation code?

**Comment by gijo-varghese** [comment] 2018-04-15 05:36
@arsanjea You can check it here: https://goo.gl/NHA3Fu

here is the code that i use: 

```
import VueApollo from "vue-apollo";
import { ApolloClient } from "apollo-client";
import { HttpLink } from "apollo-link-http";
import { InMemoryCache } from "apollo-cache-inmemory";
import { split } from "apollo-link";
import { WebSocketLink } from "apollo-link-ws";
import { getMainDefinition } from "apollo-utilities";

const httpLink = new HttpLink({
  uri: process.env.GRAPHQL_URL
});

const wsLink = new WebSocketLink({
  uri: process.env.GRAPHQL_WS_URL,
  options: {
    reconnect: true,
    lazy: true
  }
});

wsLink.subscriptionClient.on("connecting", () => {
  console.log("connecting");
});

wsLink.subscriptionClient.on("connected", () => {
  console.log("connected");
});

wsLink.subscriptionClient.on("reconnecting", () => {
  console.log("reconnecting");
});

wsLink.subscriptionClient.on("reconnected", () => {
  console.log("reconnected");
});

wsLink.subscriptionClient.on("disconnected", () => {
  console.log("disconnected");
});

wsLink.subscriptionClient.maxConnectTimeGenerator.duration = () =>
  wsLink.subscriptionClient.maxConnectTimeGenerator.max;

const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === "OperationDefinition" && operation === "subscription";
  },
  wsLink,
  httpLink
);

const apolloProvider = new VueApollo({
  defaultClient: new ApolloClient({
    link,
    cache: new InMemoryCache(),
    connectToDevTools: true
  })
});

export default apolloProvider;

```

**Comment by arsanjea** [comment] 2018-04-16 16:53
the lazy option seems to be working for me...fingers crossed!

**Comment by gijo-varghese** [comment] 2018-04-17 04:38
@arsanjea which version of `subscriptions-transport-ws` are you using in client and server?

Its working fine is localhost and problem occurs only in production servers right? From my finding, the handshake timeout is under 1 sec. So localhost it won't be a problem, but in production sometimes it may take more than 1 sec, hence everything fails. 

Is there any way I can test it? Maybe I can help

**Comment by gijo-varghese** [comment] 2018-04-17 04:38
@arsanjea This one https://goo.gl/NHA3Fu is working fine as expected, right?

**Comment by NeoPhi** [comment] 2018-04-19 13:54
@arsanjea Are you using the keep alive feature? I've observed various load balancers and proxies shutting down the WebSocket if there is no activity in a certain amount of time. We use a keep alive of 25 seconds with good results.

**Comment by gijo-varghese** [comment] 2018-04-19 15:59
I use a keep alive of 10 seconds

**Comment by slawomir-brzezinski-at-clarksons** [comment] 2018-12-19 16:19
The original reporter mentions this happens on initial connection, and [reported](https://github.com/apollographql/subscriptions-transport-ws/issues/381#issuecomment-375567893) that #377 fixed the issue.
Therefore, I suggest closing this as duplicate of #377 (and addressing that one as per [my suggestion](https://github.com/apollographql/subscriptions-transport-ws/issues/377#issuecomment-447838378) 😄).

Regarding the 'in-use' disconnections, like in @arsanjea's [comment](https://github.com/apollographql/subscriptions-transport-ws/issues/381#issuecomment-379884103), I suggest to move discussion to #483, which also fights with a similar issue and no one reported #377 as a remedy so far.

**Comment by HugoLiconV** [comment] 2020-01-23 23:59
Any other suggestion, any of this is working for me, I'm getting disconnected every minute: 
```
04:57:15 connecting
04:57:15 connected
04:58:16 disconnected
04:58:17 reconnecting
04:58:17 reconnected
```

**Comment by DominicTobias-b1** [comment] 2020-02-06 03:19
My websocket went in an infinite reconnection loop when redirecting from the login page until I added `lazy` thanks

**Comment by AndrewYefimenko** [comment] 2020-03-03 00:21
@HugoLiconV Looks like you set reconnect on client but your server is not sending "ka" (keep-alive) messages.

**Comment by geiszla** [comment] 2021-03-01 12:16
We are also experiencing this problem, but on the web (so issues referred by https://github.com/apollographql/subscriptions-transport-ws/issues/381#issuecomment-448654136 do not apply). It successfully reconnect, but because of this, we get many false `onDisconnect` events on the server and potentially lose subscriptions, because they aren't sent on the new connection.

**Closed** 2022-03-03 22:37 UTC
