### ISSUE TITLE
Cannot read .then of undefined

### ISSUE THREAD

**Issue by zackify** [apollographql/subscriptions-transport-ws#269] opened 2017-09-07 20:29 UTC
So I had to throw random console.error's into the dist of the package to find this. Here it is. I have no idea what's wrong. I'm on 0.8.2

```
TypeError: Cannot read property 'then' of undefined
    at /Users/zach/Projects/metric/server/node_modules/subscriptions-transport-ws/dist/server.js:359:19

```

<img width="758" alt="screen shot 2017-09-07 at 4 29 58 pm" src="https://user-images.githubusercontent.com/449136/30183826-d20300e6-93e9-11e7-9c37-b9743fe5dcc5.png">

    "graphql-subscriptions": "^0.4.4",
    "subscriptions-transport-ws": "^0.8.2"

**Comment by DxCx** [comment] 2017-09-14 10:14
duplicate of #259

**Closed by DxCx** 2017-09-14 10:14 UTC
